attempt to read ~/.docker/config.json for registry auths
test-kitchen/kitchen-dokken pull request #262
Opened 2022-03-08 00:29 UTC by evandam

# Description

Rough attempt to resolve #261 by reading `~/.docker/config.json` to get auths for an image's registry rather than relying on a single `creds_file` while not breaking any existing compatibility (by introducing a new `docker_config_auth` flag). I'm sure it's far from perfect, but hoping this is a good jumping off point and folks have better ideas.

I realize `image_registry = image.split('/').first` will often be misleading especially for official images on DockerHub, but might be good enough.

## Issues Resolved

Fixes #261 

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2022-05-31 18:41 UTC, ashiqueps requested changes

2022-05-31 18:41 UTC, ashiqueps commented on lib/kitchen/driver/dokken.rb
> +          username, password = Base64.decode64(v["auth"]).split(":")
Hi @evandam 

Whenever the config file has multiple registry entires and one of the registry doesn't have any credentials, this line will raise exception.
```ruby
E, [2022-06-01T00:05:44.812885 #32360] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2022-06-01T00:05:44.812915 #32360] ERROR -- Kitchen: Message: Failed to complete #create action: [undefined method `unpack1' for nil:NilClass

    str.unpack1("m")
       ^^^^^^^^]
E, [2022-06-01T00:05:44.812949 #32360] ERROR -- Kitchen: ----------------------
E, [2022-06-01T00:05:44.812979 #32360] ERROR -- Kitchen: ------Backtrace-------
E, [2022-06-01T00:05:44.813008 #32360] ERROR -- Kitchen: .rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/base64.rb:59:in `decode64'
E, [2022-06-01T00:05:44.813036 #32360] ERROR -- Kitchen: Projects/kitchen-dokken/lib/kitchen/driver/dokken.rb:443:in `block in docker_config_creds'
E, [2022-06-01T00:05:44.813070 #32360] ERROR -- Kitchen: Projects/kitchen-dokken/lib/kitchen/driver/dokken.rb:442:in `each'
E, [2022-06-01T00:05:44.813099 #32360] ERROR -- Kitchen: Projects/kitchen-dokken/lib/kitchen/driver/dokken.rb:442:in `docker_config_creds'
```
My config file: 
```json
{
   "auths": {
      "https://index.docker.io/v1/": {
         "auth": "BASE64Username&Password"
      },
      "icr.io": {},
      "public.ecr.aws": {}
   }
}
```

2022-06-16 05:19 UTC, ashiqueps approved these changes

2022-06-16 09:15 UTC, merged

2022-07-07 08:12 UTC, PJB3005 commented
This seems to break Kitchen if you don't have a `~/.docker/config.json` (file not found error) and then a nil value call if you don't have an `auths` key in it.

2022-07-19 21:21 UTC, evandam commented
Hey folks, I opened a new PR that should address this https://github.com/test-kitchen/kitchen-dokken/pull/276